"https://{default}/":
    type: upstream
    upstream: "app:http" # app name configured in sensiocloud.app.yaml
#    cache: { enabled: true }

"http://{default}/":
    type: redirect
    to: "https://{default}/"
